version: "3.9"

services:
  app:
    build: .
    ports:
    - "8080-8081:8080"
    environment:
      MEMCACHED_HOST: "memcached"
      DB_HOST: "db"
      DB_PORT: "5432"
    depends_on:
      - memcached
      - db
    volumes:
      - ./templates:/usr/src/app/templates
      - ./static:/usr/src/app/static

  memcached:
    image: memcached:latest

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./src:/var/database

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    hostname: "rabbit-devops"
