version: "3.9"

services:
  app:
    build: .
    command: bash -c "pem watch && pem migrate && python3 server.py"
    ports:
    - 8080-8081:8080
    environment:
      MEMCACHED_HOST: "memcached"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      RABBIT_HOST: "rabbit"
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
    depends_on:
      - memcached
      - db
      - rabbit
    volumes:
      - ./frontend/templates:/usr/src/app/frontend/templates
      - ./frontend/static:/usr/src/app/frontend/static
      - ./settings:/usr/src/app/settings
      - ./migrations:/usr/src/app/migrations

  memcached:
    image: memcached:latest

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.10
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rabbit:
    image: rabbitmq:3.8.14-management
    ports:
      - 15672:15672
    hostname: "rabbit-devops"
    environment:
        RABBITMQ_DEFAULT_USER: "${RABBIT_USER}"
        RABBITMQ_DEFAULT_PASSWORD: "${RABBIT_PASSWORD}"
